// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxIDe5v2x38N4uvc-oIeoL-zPMzxYxOXs',
    appId: '1:661324143928:web:df99cdf1204f93319275cd',
    messagingSenderId: '661324143928',
    projectId: 'personal-expenses-c69e0',
    authDomain: 'personal-expenses-c69e0.firebaseapp.com',
    storageBucket: 'personal-expenses-c69e0.appspot.com',
    measurementId: 'G-CDVGPWNKGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT9i2epLKsP8k37tLLWhB1VDIEfttiZYE',
    appId: '1:661324143928:android:b5e10a54331fbe169275cd',
    messagingSenderId: '661324143928',
    projectId: 'personal-expenses-c69e0',
    storageBucket: 'personal-expenses-c69e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBpJHKlinFN7OMnqYy9duq3STHxfXwBG8',
    appId: '1:661324143928:ios:a2216c97c6c1a34e9275cd',
    messagingSenderId: '661324143928',
    projectId: 'personal-expenses-c69e0',
    storageBucket: 'personal-expenses-c69e0.appspot.com',
    iosBundleId: 'com.example.personalExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBpJHKlinFN7OMnqYy9duq3STHxfXwBG8',
    appId: '1:661324143928:ios:a2216c97c6c1a34e9275cd',
    messagingSenderId: '661324143928',
    projectId: 'personal-expenses-c69e0',
    storageBucket: 'personal-expenses-c69e0.appspot.com',
    iosBundleId: 'com.example.personalExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxIDe5v2x38N4uvc-oIeoL-zPMzxYxOXs',
    appId: '1:661324143928:web:6ec3daf270a61d679275cd',
    messagingSenderId: '661324143928',
    projectId: 'personal-expenses-c69e0',
    authDomain: 'personal-expenses-c69e0.firebaseapp.com',
    storageBucket: 'personal-expenses-c69e0.appspot.com',
    measurementId: 'G-SQ7YT93EVE',
  );
}
